[project]
name = "swift_needle"
version = "0.1.0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "torch==2.10.0",
    "coreai-torch==0.4.0",
    "huggingface_hub>=1.21.0",
    "safetensors>=0.6.2",
    "sentencepiece>=0.2.1",
    "tokenizers>=0.22.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["swift_needle"]
package-dir = {swift_needle = "swift_needle"}
